# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes: 
      - ./:/usr/app
      - /usr/app/node_modules
    depends_on:
      - sol
    environment:
    command: npm run dev

  sol:
    image: ethereum/solc:0.5.4
    tty: true
    volumes: 
      - ./contracts:/sources

