# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes: 
      - ./:/usr/app
      - /usr/app/node_modules
    command: sh
